In [2]:
from __future__ import print_function
import torch

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[ 1.1860e-29,  3.0809e-41,  1.1054e-09],
        [ 4.5591e-41, -4.1819e-37,  4.5590e-41],
        [ 6.8664e-44,  0.0000e+00,  1.1862e-29],
        [ 3.0809e-41,  1.1054e-09,  4.5591e-41],
        [-4.2027e-37,  4.5590e-41, -4.2028e-37]])


In [4]:
x=torch.rand(5,3)
print(x)

tensor([[0.1147, 0.5640, 0.2136],
        [0.4316, 0.3440, 0.4169],
        [0.0566, 0.1931, 0.3036],
        [0.8089, 0.7455, 0.9396],
        [0.2814, 0.6805, 0.3140]])


In [5]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0190,  0.3855,  0.2517],
        [ 2.9189,  0.4468, -0.6517],
        [-0.7153,  0.3415,  0.2889],
        [-1.0926, -0.8706,  1.7726],
        [-1.2567, -1.0732,  0.4483]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
print(x.shape)

torch.Size([5, 3])


In [6]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 0.5182,  0.7271,  0.4441],
        [ 3.6867,  1.1494, -0.6232],
        [-0.5392,  0.6693,  0.8767],
        [-0.3225, -0.6723,  2.6224],
        [-0.5229, -1.0648,  0.8843]])


In [14]:
print(torch.add(x,y))

tensor([[ 1.6882, -0.0842,  0.9578],
        [ 1.6676, -0.5837,  0.5199],
        [-0.4359,  2.4491,  0.4298],
        [-1.0946, -0.1215,  1.6273],
        [-0.1728,  1.9572,  0.5149]])


In [16]:
result=torch.empty(5,3)
torch.add(x,y,out=result)  # 提供输出tensor作为参数
print(result)

tensor([[ 1.6882, -0.0842,  0.9578],
        [ 1.6676, -0.5837,  0.5199],
        [-0.4359,  2.4491,  0.4298],
        [-1.0946, -0.1215,  1.6273],
        [-0.1728,  1.9572,  0.5149]])


In [10]:
y.add_(x)  # 任何以_结尾的操作，都会替换原始变量
print(y)

tensor([[ 0.5182,  0.7271,  0.4441],
        [ 3.6867,  1.1494, -0.6232],
        [-0.5392,  0.6693,  0.8767],
        [-0.3225, -0.6723,  2.6224],
        [-0.5229, -1.0648,  0.8843]])


In [11]:
print(y)

tensor([[ 0.5182,  0.7271,  0.4441],
        [ 3.6867,  1.1494, -0.6232],
        [-0.5392,  0.6693,  0.8767],
        [-0.3225, -0.6723,  2.6224],
        [-0.5229, -1.0648,  0.8843]])


In [12]:
print(x[:,1])

tensor([ 0.3855,  0.4468,  0.3415, -0.8706, -1.0732])


In [13]:
x=torch.randn(4,4)
y=x.view(16)  # view与reshape类似
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.7559])
-0.7558967471122742


In [16]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [19]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [20]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
if torch.cuda.is_available():
    device=torch.device("cuda")  # 一个cuda设备对象
    y=torch.ones_like(x,device=device) #从GPU创建张量
    x=x.to(device) #将张量移动到cuda中
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))  # “.to”也会对变量的类型做更改

tensor([0.2441], device='cuda:0')
tensor([0.2441], dtype=torch.float64)
