In [1]:
import torch
import numpy as np
torch.__version__

'1.0.1.post2'

In [2]:
x=torch.rand(2,3)

In [3]:
x

tensor([[0.5377, 0.0430, 0.6023],
        [0.5582, 0.6585, 0.2767]])

In [4]:
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [5]:
y=torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.1671, 0.6415, 0.9113, 0.8482, 0.5559],
          [0.0179, 0.9606, 0.8086, 0.0790, 0.2697],
          [0.6972, 0.4565, 0.5139, 0.7354, 0.7594],
          [0.9081, 0.8767, 0.4816, 0.8157, 0.9705]],

         [[0.3523, 0.4582, 0.9269, 0.1317, 0.5118],
          [0.4718, 0.3737, 0.2796, 0.8101, 0.1457],
          [0.7216, 0.7433, 0.3988, 0.6856, 0.8200],
          [0.4752, 0.0289, 0.1679, 0.3271, 0.4455]],

         [[0.4345, 0.7406, 0.8038, 0.4441, 0.4123],
          [0.5255, 0.5877, 0.4869, 0.3346, 0.0792],
          [0.4579, 0.8724, 0.1696, 0.6146, 0.8842],
          [0.4134, 0.8037, 0.1277, 0.4113, 0.2882]]],


        [[[0.8370, 0.6021, 0.0473, 0.7110, 0.7378],
          [0.3380, 0.6422, 0.6878, 0.4286, 0.9613],
          [0.4980, 0.4775, 0.8720, 0.7986, 0.1024],
          [0.1149, 0.9237, 0.9078, 0.4555, 0.8549]],

         [[0.9921, 0.4111, 0.2846, 0.4292, 0.3737],
          [0.0701, 0.1419, 0.4694, 0.7538, 0.0372],
          [0.9243, 0.9955, 0.0822, 0.3478, 0.3466],
  

In [6]:
scalar=torch.tensor(3.14222) # 直接使用现有数字生成
print(scalar)
scalar.size()

tensor(3.1422)


torch.Size([])

In [7]:
scalar.item()

3.1422200202941895

In [8]:
tensor=torch.tensor([3.142323])
print(tensor)
tensor.size()

tensor([3.1423])


torch.Size([1])

In [9]:
tensor.item() # 张量中只有一个元素也可以调用item

3.1423230171203613

In [10]:
long=tensor.long()
long

tensor([3])

In [11]:
int_t=tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [12]:
a=torch.randn((3,2))
numpy_a=a.numpy() # tensor转换为numpy
print(numpy_a)

[[-0.6619309  -0.54787374]
 [ 0.4030662   0.23653856]
 [ 1.3325671   0.34952483]]


In [13]:
torch_a=torch.from_numpy(numpy_a) # numpy转化为tensor
torch_a

tensor([[-0.6619, -0.5479],
        [ 0.4031,  0.2365],
        [ 1.3326,  0.3495]])

In [14]:
cpu_a=torch.rand(4,3)
cpu_a.type()

'torch.FloatTensor'

In [15]:
gpu_a=cpu_a.cuda()  # 从CPU移到GPU
gpu_a.type()

'torch.cuda.FloatTensor'

In [16]:
cpu_b=gpu_a.cpu() # 从GPU到CPU
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
gpu_b=cpu_b.to(device)
gpu_b.type()

cuda


'torch.cuda.FloatTensor'

In [17]:
x = torch.randn(3, 3)
max_value,max_idx=torch.max(x,dim=1)
print(max_value,max_idx)

tensor([ 1.7325, -0.0469,  1.0035]) tensor([2, 2, 1])


In [20]:
y=torch.randn(3,3)
x.add_(y)
print(x)

tensor([[-0.6761,  2.0759,  2.7236],
        [-0.3316, -1.5625,  0.6100],
        [-0.8383,  0.2733,  0.1697]])
